bt_navigator:
  ros__parameters:
    use_sim_time: false
    enable_groot_monitoring: true
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    default_nav_to_pose_bt_xml: "navigate_to_pose_w_replanning_and_recovery.xml"
    default_nav_through_poses_bt_xml: "navigate_through_poses_w_replanning_and_recovery.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node


controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0 #20.0
    min_x_velocity_threshold: 0.0
    min_y_velocity_threshold: 0.0
    min_theta_velocity_threshold: 0.0 #0.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.05
      movement_time_allowance: 10.0 #10.0

    # Goal checker parameters
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.1 
      yaw_goal_tolerance: 6.25 #0.1
      stateful: false
    # DWB parameterss
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      short_circuit_trajectory_evaluation: true
      debug_trajectory_details: True
      # Multiplicateur de 1.0875
      min_vel_x: -6.0
      max_vel_x: 6.0
      min_vel_y: -5.5
      max_vel_y: 5.5
      min_speed_xy: -5.0
      max_speed_xy: 5.0
      min_speed_theta: -1.48
      max_vel_theta: 1.48
      #Distance durant laquelle le robot accélère
      acc_lim_x: 12.0 #3.0
      acc_lim_y: 12.0 #3.0
      acc_lim_theta: 3.0 #3.0
      decel_lim_x: -0.5
      decel_lim_y: -0.5
      decel_lim_theta: -0.5
      # stateful: true
      critics: ["GoalDist"]

      # BaseObstacle.scale: 0.02
      # PathAlign.scale: 2.0
      # PathAlign.forward_point_distance: 0.1
      # GoalAlign.scale: 24.0
      # GoalAlign.forward_point_distance: 0.1
      # PathDist.scale: 16.0
      GoalDist.scale: 1.0
      # RotateToGoal.scale: 8.0
      # RotateToGoal.slowing_factor: 5.0
      # RotateToGoal.lookahead_time: -1.0

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0 #5.0
      publish_frequency: 2.0 #2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05 #0.1
      robot_radius: 0.085 #0.085
      plugins: ["static_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        # map_subscribe_transient_local: True
      rostron_obstacle_layer:
        plugin: rostron_nav_costmap_plugin/ObstacleLayer
        enabled: false
        robot_id: 0
        team: 'yellow'
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      always_send_full_costmap: True
      height: 7
      width: 10
      origin_x: -4.9
      origin_y: -3.4
      resolution: 0.1
      observation_sources: "static_layer rostron_obstacle_layer"
      update_frequency: 1.0
      robot_radius: 0.085
      track_unknown_space: true
      plugins: ["static_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
      rostron_obstacle_layer:
        plugin: rostron_nav_costmap_plugin/ObstacleLayer
        enabled: True
        robot_id: 0
        team: 'yellow'

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"   
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200