yellow:
  vision:
    ros__parameters:
      port: 10020

  sim_sender:
    ros__parameters:
      port: 10302
  
  filter:
    ros__parameters:
      publish_robots : [0]

blue:
  vision:
    ros__parameters:
      port: 10020

  sim_sender:
    ros__parameters:
      port: 10301
  
  filter:
    ros__parameters:
      publish_robots : [0]