yellow:
  vision:
    ros__parameters:
      port: 10020

  sim_sender:
    ros__parameters:
      port: 10302

  aggregate:
    ros__parameters:
      publish_robots: [0, 1, 2, 3, 4, 5]
      yellow: True

blue:
  vision:
    ros__parameters:
      port: 10020

  sim_sender:
    ros__parameters:
      port: 10301

  aggregate:
    ros__parameters:
      publish_robots: [0, 1, 2, 3, 4, 5]
      yellow: False
